### ISSUE TITLE
ls does not work with sbt 0.13.8 

### ISSUE THREAD

**Issue by altcoder** [softprops/ls#75]
ls command causes:

`java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ScalaSigSymbol`

Probably related to this issue:
https://github.com/json4s/json4s/issues/236
